INSERT INTO movie (movie_title, genre, release_year, picture, trailer) VALUES ('The Fast and the Furious', 'Action', 2001, 'https://www.imdb.com/title/tt0232500/mediaviewer/rm3153527296/', 'https://www.imdb.com/video/vi2048898073?playlistId=tt0232500&ref_=tt_ov_vi');
INSERT INTO movie (movie_title, genre, release_year, picture, trailer) VALUES ('2 Fast 2 Furious', 'Action', 2003, 'https://www.imdb.com/title/tt0322259/mediaviewer/rm808455680/', 'https://www.imdb.com/video/vi2897412377?playlistId=tt0322259&ref_=tt_ov_vi');
INSERT INTO movie (movie_title, genre, release_year, picture, trailer) VALUES ('The Fast and the Furious: Tokyo Drift', 'Action', 2006, 'https://www.imdb.com/title/tt0463985/mediaviewer/rm296653312/', 'https://www.imdb.com/video/vi2324431129?ref_=ttvi_vi_imdb_8');
INSERT INTO movie (movie_title, genre, release_year, picture, trailer) VALUES ('Fast & Furious', 'Action', 2009, 'https://www.imdb.com/title/tt1013752/mediaviewer/rm1916359168/', 'https://www.imdb.com/video/vi2299986713?playlistId=tt1013752&ref_=tt_ov_vi');
INSERT INTO movie (movie_title, genre, release_year, picture, trailer) VALUES ('Fast Five', 'Action', 2011, 'https://www.imdb.com/title/tt1596343/mediaviewer/rm1398323968/', 'https://www.imdb.com/video/vi1723702553?playlistId=tt1596343&ref_=tt_ov_vi');
INSERT INTO movie (movie_title, genre, release_year, picture, trailer) VALUES ('Fast & Furious 6', 'Action', 2013, 'https://www.imdb.com/title/tt1905041/mediaviewer/rm3465715968/', 'https://www.imdb.com/video/vi3225003545?playlistId=tt1905041&ref_=tt_ov_vi');
INSERT INTO movie (movie_title, genre, release_year, picture, trailer) VALUES ('Furious 7', 'Action', 2015, 'https://www.imdb.com/title/tt2820852/mediaviewer/rm3501718272/', 'https://www.imdb.com/video/vi1346743833?playlistId=tt2820852&ref_=tt_ov_vi');
INSERT INTO movie (movie_title, genre, release_year, picture, trailer) VALUES ('The Fate of the Furious', 'Action', 2017, 'https://www.imdb.com/title/tt4630562/mediaviewer/rm2675061248/?ref_=tt_ov_i', 'https://www.imdb.com/video/vi1498461721?playlistId=tt4630562&ref_=tt_ov_vi');
INSERT INTO movie (movie_title, genre, release_year, picture, trailer) VALUES ('F9: The Fast Saga', 'Action', 2019, 'https://www.imdb.com/title/tt5433138/mediaviewer/rm2544353793/', 'https://www.imdb.com/video/vi3757621273?playlistId=tt5433138&ref_=tt_ov_vi');
INSERT INTO actor (name, alias, gender, picture) VALUES ('Vin Diesel', 'Dominic Toretto', 'MALE', 'https://www.imdb.com/name/nm0004874/mediaviewer/rm4004029184/');
INSERT INTO actor (name, alias, gender, picture) VALUES ('Paul Walker', E'Brian O\‘ Connor', 'MALE', 'https://www.imdb.com/name/nm0908094/mediaviewer/rm3313535744/');
INSERT INTO actor (name, alias, gender, picture) VALUES ('Michelle Rodriguez', 'Letty', 'FEMALE', 'https://www.imdb.com/name/nm0735442/mediaviewer/rm2927663616/');
INSERT INTO actor (name, alias, gender, picture) VALUES ('Jordana Brewster', 'Mia Toretto', 'FEMALE', 'https://www.imdb.com/name/nm0108287/mediaviewer/rm57546752/');
INSERT INTO actor (name, alias, gender, picture) VALUES ('Matt Schulze', 'Vince', 'MALE', 'https://www.imdb.com/name/nm0776580/mediaviewer/rm4294283776?ref_=nm_ov_ph');
INSERT INTO actor (name, alias, gender, picture) VALUES ('Tyrese Gibson', 'Roman Pearce', 'MALE', 'https://www.imdb.com/name/nm0879085/mediaviewer/rm3701338368/');
INSERT INTO actor (name, alias, gender, picture) VALUES ('Ludacris', 'Tej', 'MALE', 'https://www.imdb.com/name/nm0524839/mediaviewer/rm1586402304/');
INSERT INTO actor (name, alias, gender, picture) VALUES ('Dwayne Johnson', 'Hobbs', 'MALE', 'https://www.imdb.com/name/nm0425005/mediaviewer/rm3093231104/');
INSERT INTO actor (name, alias, gender, picture) VALUES ('Sung Kang', 'Han', 'MALE', 'https://www.imdb.com/name/nm0437646/mediaviewer/rm3973565441/');
INSERT INTO actor (name, alias, gender, picture) VALUES ('Gal Gadot', 'Gisele', 'FEMALE', 'https://www.imdb.com/name/nm2933757/mediaviewer/rm1174257921/');
INSERT INTO actor (name, alias, gender, picture) VALUES ('Elsa Pataky', 'Elena', 'FEMALE', 'https://www.imdb.com/name/nm0665235/mediaviewer/rm159031296/');
INSERT INTO actor (name, alias, gender, picture) VALUES ('Jason Statham', 'Deckard Shaw', 'MALE', 'https://www.imdb.com/name/nm0005458/mediaviewer/rm2311886080/');
INSERT INTO actor (name, alias, gender, picture) VALUES ('Luke Evans', 'Owen Shaw', 'MALE', 'https://www.imdb.com/name/nm1812656/mediaviewer/rm4051150592/');
INSERT INTO actor (name, alias, gender, picture) VALUES ('Charlize Theron', 'Cipher', 'FEMALE', 'https://www.imdb.com/name/nm0000234/mediaviewer/rm2942012672/');
INSERT INTO actor (name, alias, gender, picture) VALUES ('Nathalie Emmanuel', 'Ramsey', 'FEMALE', 'https://www.imdb.com/name/nm2812026/mediaviewer/rm3887574016/');
INSERT INTO actor (name, alias, gender, picture) VALUES ('Lucas Black', 'Sean Boswell', 'MALE', 'https://www.imdb.com/name/nm0085407/mediaviewer/rm1967502592/');
INSERT INTO franchise(name, description) VALUES ('Fast and Furious', 'Fast & Furious (also known as The Fast and the Furious and The Fast Saga) is a media franchise centered on a series of action films that are largely concerned with illegal street racing, heists, spies and family. The franchise also includes short films, a television series, live shows, video games and theme park attractions. It is distributed by Universal Pictures.');
INSERT INTO franchise(name, description) VALUES ('Walt Disney', 'The Walt Disney Company, commonly known as Disney is an American multinational entertainment and media conglomerate headquartered at the Walt Disney Studios complex in Burbank, California.');
INSERT INTO franchise(name, description) VALUES ('Marvel Cinematic Universe', 'The Marvel Cinematic Universe (MCU) is an American media franchise and shared universe centered on a series of superhero films produced by Marvel Studios. The films are based on characters that appear in American comic books published by Marvel Comics. The franchise also includes television series, short films, digital series, and literature. The shared universe, much like the original Marvel Universe in comic books, was established by crossing over common plot elements, settings, cast, and characters.');
INSERT INTO franchise_movies SELECT 1, 1;
INSERT INTO franchise_movies SELECT 1, 2;
INSERT INTO franchise_movies SELECT 1, 3;
INSERT INTO franchise_movies SELECT 1, 4;
INSERT INTO franchise_movies SELECT 1, 5;
INSERT INTO franchise_movies SELECT 1, 6;
INSERT INTO franchise_movies SELECT 1, 7;
INSERT INTO franchise_movies SELECT 1, 8;
INSERT INTO franchise_movies SELECT 1, 9;
INSERT INTO actor_movie SELECT 1, 1;
INSERT INTO actor_movie SELECT 1, 2;
INSERT INTO actor_movie SELECT 1, 3;
INSERT INTO actor_movie SELECT 1, 4;
INSERT INTO actor_movie SELECT 1, 5;
INSERT INTO actor_movie SELECT 2, 2;
INSERT INTO actor_movie SELECT 2, 6;
INSERT INTO actor_movie SELECT 2, 7;
INSERT INTO actor_movie SELECT 3, 16;
INSERT INTO actor_movie SELECT 4, 1;
INSERT INTO actor_movie SELECT 4, 2;
INSERT INTO actor_movie SELECT 4, 3;
INSERT INTO actor_movie SELECT 4, 4;
INSERT INTO actor_movie SELECT 5, 1;
INSERT INTO actor_movie SELECT 5, 2;
INSERT INTO actor_movie SELECT 5, 3;
INSERT INTO actor_movie SELECT 5, 4;
INSERT INTO actor_movie SELECT 6, 1;
INSERT INTO actor_movie SELECT 6, 2;
INSERT INTO actor_movie SELECT 6, 3;
INSERT INTO actor_movie SELECT 6, 4;
INSERT INTO actor_movie SELECT 7, 1;
INSERT INTO actor_movie SELECT 7, 2;
INSERT INTO actor_movie SELECT 7, 3;
INSERT INTO actor_movie SELECT 7, 4;
INSERT INTO actor_movie SELECT 8, 1;
INSERT INTO actor_movie SELECT 8, 2;
INSERT INTO actor_movie SELECT 8, 3;
INSERT INTO actor_movie SELECT 8, 4;
INSERT INTO actor_movie SELECT 9, 1;
INSERT INTO actor_movie SELECT 9, 2;
INSERT INTO actor_movie SELECT 9, 3;
INSERT INTO actor_movie SELECT 9, 4;
